### ISSUE TITLE
👩‍🌾 test_launch_ros segfaults on Foxy nightly

### ISSUE THREAD

**Issue by chapulina** [ros2/launch_ros#262] opened 2021-08-26 16:20 UTC
## Bug report

**Required Info:**

- Operating System: Ubuntu Focal
- Installation type: Source
- Version or commit hash: 874412408e1077b9b38de5ee3ff8a0de6481c05f
- DDS implementation: CycloneDDS
- Client library (if applicable): rclpy

#### Steps to reproduce issue

I'm not sure if it's a spurious failure or if it will persist. We should keep an eye on the nightlies:

https://build.ros2.org/view/Fci/job/Fci__nightly-cyclonedds_ubuntu_focal_amd64/308/consoleFull#console-section-1634

#### Expected behavior

Nightly passes

#### Actual behavior

Package failed during `colcon test`

#### Additional information

Failed with segmentation faults:

```
01:43:16 test/test_launch_ros/actions/test_lifecycle_node.py ..                   [  7%]
01:43:20 Fatal Python error: Segmentation fault
```

and 

```
01:43:21 test/test_launch_ros/actions/test_load_composable_nodes.py ...--- stderr: test_launch_ros
01:43:21 Fatal Python error: Segmentation fault
```

<details><summary>Full log</summary>
<p>

```
01:43:10 Starting >>> test_launch_ros
01:43:11 ============================= test session starts ==============================
01:43:11 platform linux -- Python 3.8.10, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
01:43:11 cachedir: /tmp/ws/build_isolated/test_launch_ros/.pytest_cache
01:43:11 rootdir: /tmp/ws/src/ros2/launch_ros/test_launch_ros
01:43:11 plugins: ament-copyright-0.9.6, ament-pep257-0.9.6, ament-flake8-0.9.6, ament-lint-0.9.6, rerunfailures-10.1, mock-1.10.4, cov-2.8.1, colcon-core-0.6.1
01:43:11 collected 103 items
01:43:11 
01:43:11 test/test_copyright.py .                                                 [  0%]
01:43:11 test/test_flake8.py .                                                    [  1%]
01:43:11 test/test_pep257.py .                                                    [  2%]
01:43:16 test/test_launch_ros/actions/test_composable_node_container.py ...       [  5%]
01:43:16 test/test_launch_ros/actions/test_lifecycle_node.py ..                   [  7%]
01:43:20 Fatal Python error: Segmentation fault
01:43:20 
01:43:20 Current thread 0x00007fdbc6ffd700 (most recent call first):
01:43:20   File "/tmp/ws/install_isolated/rclpy/lib/python3.8/site-packages/rclpy/executors.py", line 586 in _wait_for_ready_callbacks
01:43:20   File "/tmp/ws/install_isolated/rclpy/lib/python3.8/site-packages/rclpy/executors.py", line 689 in wait_for_ready_callbacks
01:43:20   File "/tmp/ws/install_isolated/rclpy/lib/python3.8/site-packages/rclpy/executors.py", line 703 in spin_once
01:43:20   File "/tmp/ws/install_isolated/rclpy/lib/python3.8/site-packages/rclpy/__init__.py", line 191 in spin
01:43:20   File "/usr/lib/python3.8/threading.py", line 870 in run
01:43:20   File "/usr/lib/python3.8/threading.py", line 932 in _bootstrap_inner
01:43:20   File "/usr/lib/python3.8/threading.py", line 890 in _bootstrap
01:43:20 
01:43:20 Thread 0x00007fdbc67fc700 (most recent call first):
01:43:20   File "/usr/lib/python3.8/concurrent/futures/thread.py", line 78 in _worker
01:43:20   File "/usr/lib/python3.8/threading.py", line 870 in run
01:43:20   File "/usr/lib/python3.8/threading.py", line 932 in _bootstrap_inner
01:43:20   File "/usr/lib/python3.8/threading.py", line 890 in _bootstrap
01:43:20 
01:43:20 Thread 0x00007fdbe295f740 (most recent call first):
01:43:20   File "/tmp/ws/install_isolated/rclpy/lib/python3.8/site-packages/rclpy/handle.py", line 138 in __destroy
01:43:20   File "/tmp/ws/install_isolated/rclpy/lib/python3.8/site-packages/rclpy/handle.py", line 95 in destroy
01:43:20   File "/tmp/ws/install_isolated/rclpy/lib/python3.8/site-packages/rclpy/publisher.py", line 93 in destroy
01:43:20   File "/tmp/ws/install_isolated/rclpy/lib/python3.8/site-packages/rclpy/node.py", line 1398 in destroy_publisher
01:43:20   File "/tmp/ws/install_isolated/rclpy/lib/python3.8/site-packages/rclpy/node.py", line 1517 in destroy_node
01:43:20   File "/tmp/ws/src/ros2/launch_ros/test_launch_ros/test/test_launch_ros/actions/test_load_composable_nodes.py", line 79 in shutdown
01:43:20   File "/tmp/ws/src/ros2/launch_ros/test_launch_ros/test/test_launch_ros/actions/test_load_composable_nodes.py", line 120 in mock_component_container
01:43:20   File "/usr/local/lib/python3.8/dist-packages/_pytest/fixtures.py", line 941 in _teardown_yield_fixture
01:43:20   File "/usr/local/lib/python3.8/dist-packages/_pytest/fixtures.py", line 1027 in finish
01:43:20   File "/usr/local/lib/python3.8/dist-packages/_pytest/runner.py", line 395 in _callfinalizers
01:43:20   File "/usr/local/lib/python3.8/dist-packages/_pytest/runner.py", line 405 in _teardown_with_finalization
01:43:20   File "/usr/local/lib/python3.8/dist-packages/_pytest/runner.py", line 387 in _pop_and_teardown
01:43:20   File "/usr/local/lib/python3.8/dist-packages/_pytest/runner.py", line 427 in _teardown_towards
01:43:20   File "/usr/local/lib/python3.8/dist-packages/_pytest/runner.py", line 419 in teardown_exact
01:43:20   File "/usr/local/lib/python3.8/dist-packages/_pytest/runner.py", line 175 in pytest_runtest_teardown
01:43:20   File "/usr/local/lib/python3.8/dist-packages/pluggy/callers.py", line 187 in _multicall
01:43:20   File "/usr/local/lib/python3.8/dist-packages/pluggy/manager.py", line 84 in <lambda>
01:43:20   File "/usr/local/lib/python3.8/dist-packages/pluggy/manager.py", line 93 in _hookexec
01:43:20   File "/usr/local/lib/python3.8/dist-packages/pluggy/hooks.py", line 286 in __call__
01:43:20   File "/usr/local/lib/python3.8/dist-packages/_pytest/runner.py", line 255 in <lambda>
01:43:20   File "/usr/local/lib/python3.8/dist-packages/_pytest/runner.py", line 311 in from_call
01:43:20   File "/usr/local/lib/python3.8/dist-packages/_pytest/runner.py", line 254 in call_runtest_hook
01:43:20   File "/usr/local/lib/python3.8/dist-packages/_pytest/runner.py", line 215 in call_and_report
01:43:20   File "/usr/local/lib/python3.8/dist-packages/_pytest/runner.py", line 127 in runtestprotocol
01:43:20   File "/usr/local/lib/python3.8/dist-packages/_pytest/runner.py", line 109 in pytest_runtest_protocol
01:43:20   File "/usr/local/lib/python3.8/dist-packages/pluggy/callers.py", line 187 in _multicall
01:43:20   File "/usr/local/lib/python3.8/dist-packages/pluggy/manager.py", line 84 in <lambda>
01:43:20   File "/usr/local/lib/python3.8/dist-packages/pluggy/manager.py", line 93 in _hookexec
01:43:20   File "/usr/local/lib/python3.8/dist-packages/pluggy/hooks.py", line 286 in __call__
01:43:20   File "/usr/local/lib/python3.8/dist-packages/_pytest/main.py", line 348 in pytest_runtestloop
01:43:20   File "/usr/local/lib/python3.8/dist-packages/pluggy/callers.py", line 187 in _multicall
01:43:20   File "/usr/local/lib/python3.8/dist-packages/pluggy/manager.py", line 84 in <lambda>
01:43:20   File "/usr/local/lib/python3.8/dist-packages/pluggy/manager.py", line 93 in _hookexec
01:43:20   File "/usr/local/lib/python3.8/dist-packages/pluggy/hooks.py", line 286 in __call__
01:43:20   File "/usr/local/lib/python3.8/dist-packages/_pytest/main.py", line 323 in _main
01:43:20   File "/usr/local/lib/python3.8/dist-packages/_pytest/main.py", line 269 in wrap_session
01:43:20   File "/usr/local/lib/python3.8/dist-packages/_pytest/main.py", line 316 in pytest_cmdline_main
01:43:20   File "/usr/local/lib/python3.8/dist-packages/pluggy/callers.py", line 187 in _multicall
01:43:20   File "/usr/local/lib/python3.8/dist-packages/pluggy/manager.py", line 84 in <lambda>
01:43:20   File "/usr/local/lib/python3.8/dist-packages/pluggy/manager.py", line 93 in _hookexec
01:43:20   File "/usr/local/lib/python3.8/dist-packages/pluggy/hooks.py", line 286 in __call__
01:43:20   File "/usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py", line 162 in main
01:43:20   File "/usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py", line 185 in console_main
01:43:20   File "/usr/local/lib/python3.8/dist-packages/pytest/__main__.py", line 5 in <module>
01:43:20   File "/usr/lib/python3.8/runpy.py", line 87 in _run_code
01:43:20   File "/usr/lib/python3.8/runpy.py", line 194 in _run_module_as_main
01:43:21 test/test_launch_ros/actions/test_load_composable_nodes.py ...--- stderr: test_launch_ros
01:43:21 Fatal Python error: Segmentation fault
01:43:21 
01:43:21 Current thread 0x00007fdbc6ffd700 (most recent call first):
01:43:21   File "/tmp/ws/install_isolated/rclpy/lib/python3.8/site-packages/rclpy/executors.py", line 586 in _wait_for_ready_callbacks
01:43:21   File "/tmp/ws/install_isolated/rclpy/lib/python3.8/site-packages/rclpy/executors.py", line 689 in wait_for_ready_callbacks
01:43:21   File "/tmp/ws/install_isolated/rclpy/lib/python3.8/site-packages/rclpy/executors.py", line 703 in spin_once
01:43:21   File "/tmp/ws/install_isolated/rclpy/lib/python3.8/site-packages/rclpy/__init__.py", line 191 in spin
01:43:21   File "/usr/lib/python3.8/threading.py", line 870 in run
01:43:21   File "/usr/lib/python3.8/threading.py", line 932 in _bootstrap_inner
01:43:21   File "/usr/lib/python3.8/threading.py", line 890 in _bootstrap
01:43:21 
01:43:21 Thread 0x00007fdbc67fc700 (most recent call first):
01:43:21   File "/usr/lib/python3.8/concurrent/futures/thread.py", line 78 in _worker
01:43:21   File "/usr/lib/python3.8/threading.py", line 870 in run
01:43:21   File "/usr/lib/python3.8/threading.py", line 932 in _bootstrap_inner
01:43:21   File "/usr/lib/python3.8/threading.py", line 890 in _bootstrap
01:43:21 
01:43:21 Thread 0x00007fdbe295f740 (most recent call first):
01:43:21   File "/tmp/ws/install_isolated/rclpy/lib/python3.8/site-packages/rclpy/handle.py", line 138 in __destroy
01:43:21   File "/tmp/ws/install_isolated/rclpy/lib/python3.8/site-packages/rclpy/handle.py", line 95 in destroy
01:43:21   File "/tmp/ws/install_isolated/rclpy/lib/python3.8/site-packages/rclpy/publisher.py", line 93 in destroy
01:43:21   File "/tmp/ws/install_isolated/rclpy/lib/python3.8/site-packages/rclpy/node.py", line 1398 in destroy_publisher
01:43:21   File "/tmp/ws/install_isolated/rclpy/lib/python3.8/site-packages/rclpy/node.py", line 1517 in destroy_node
01:43:21   File "/tmp/ws/src/ros2/launch_ros/test_launch_ros/test/test_launch_ros/actions/test_load_composable_nodes.py", line 79 in shutdown
01:43:21   File "/tmp/ws/src/ros2/launch_ros/test_launch_ros/test/test_launch_ros/actions/test_load_composable_nodes.py", line 120 in mock_component_container
01:43:21   File "/usr/local/lib/python3.8/dist-packages/_pytest/fixtures.py", line 941 in _teardown_yield_fixture
01:43:21   File "/usr/local/lib/python3.8/dist-packages/_pytest/fixtures.py", line 1027 in finish
01:43:21   File "/usr/local/lib/python3.8/dist-packages/_pytest/runner.py", line 395 in _callfinalizers
01:43:21   File "/usr/local/lib/python3.8/dist-packages/_pytest/runner.py", line 405 in _teardown_with_finalization
01:43:21   File "/usr/local/lib/python3.8/dist-packages/_pytest/runner.py", line 387 in _pop_and_teardown
01:43:21   File "/usr/local/lib/python3.8/dist-packages/_pytest/runner.py", line 427 in _teardown_towards
01:43:21   File "/usr/local/lib/python3.8/dist-packages/_pytest/runner.py", line 419 in teardown_exact
01:43:21   File "/usr/local/lib/python3.8/dist-packages/_pytest/runner.py", line 175 in pytest_runtest_teardown
01:43:21   File "/usr/local/lib/python3.8/dist-packages/pluggy/callers.py", line 187 in _multicall
01:43:21   File "/usr/local/lib/python3.8/dist-packages/pluggy/manager.py", line 84 in <lambda>
01:43:21   File "/usr/local/lib/python3.8/dist-packages/pluggy/manager.py", line 93 in _hookexec
01:43:21   File "/usr/local/lib/python3.8/dist-packages/pluggy/hooks.py", line 286 in __call__
01:43:21   File "/usr/local/lib/python3.8/dist-packages/_pytest/runner.py", line 255 in <lambda>
01:43:21   File "/usr/local/lib/python3.8/dist-packages/_pytest/runner.py", line 311 in from_call
01:43:21   File "/usr/local/lib/python3.8/dist-packages/_pytest/runner.py", line 254 in call_runtest_hook
01:43:21   File "/usr/local/lib/python3.8/dist-packages/_pytest/runner.py", line 215 in call_and_report
01:43:21   File "/usr/local/lib/python3.8/dist-packages/_pytest/runner.py", line 127 in runtestprotocol
01:43:21   File "/usr/local/lib/python3.8/dist-packages/_pytest/runner.py", line 109 in pytest_runtest_protocol
01:43:21   File "/usr/local/lib/python3.8/dist-packages/pluggy/callers.py", line 187 in _multicall
01:43:21   File "/usr/local/lib/python3.8/dist-packages/pluggy/manager.py", line 84 in <lambda>
01:43:21   File "/usr/local/lib/python3.8/dist-packages/pluggy/manager.py", line 93 in _hookexec
01:43:21   File "/usr/local/lib/python3.8/dist-packages/pluggy/hooks.py", line 286 in __call__
01:43:21   File "/usr/local/lib/python3.8/dist-packages/_pytest/main.py", line 348 in pytest_runtestloop
01:43:21   File "/usr/local/lib/python3.8/dist-packages/pluggy/callers.py", line 187 in _multicall
01:43:21   File "/usr/local/lib/python3.8/dist-packages/pluggy/manager.py", line 84 in <lambda>
01:43:21   File "/usr/local/lib/python3.8/dist-packages/pluggy/manager.py", line 93 in _hookexec
01:43:21   File "/usr/local/lib/python3.8/dist-packages/pluggy/hooks.py", line 286 in __call__
01:43:21   File "/usr/local/lib/python3.8/dist-packages/_pytest/main.py", line 323 in _main
01:43:21   File "/usr/local/lib/python3.8/dist-packages/_pytest/main.py", line 269 in wrap_session
01:43:21   File "/usr/local/lib/python3.8/dist-packages/_pytest/main.py", line 316 in pytest_cmdline_main
01:43:21   File "/usr/local/lib/python3.8/dist-packages/pluggy/callers.py", line 187 in _multicall
01:43:21   File "/usr/local/lib/python3.8/dist-packages/pluggy/manager.py", line 84 in <lambda>
01:43:21   File "/usr/local/lib/python3.8/dist-packages/pluggy/manager.py", line 93 in _hookexec
01:43:21   File "/usr/local/lib/python3.8/dist-packages/pluggy/hooks.py", line 286 in __call__
01:43:21   File "/usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py", line 162 in main
01:43:21   File "/usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py", line 185 in console_main
01:43:21   File "/usr/local/lib/python3.8/dist-packages/pytest/__main__.py", line 5 in <module>
01:43:21   File "/usr/lib/python3.8/runpy.py", line 87 in _run_code
01:43:21   File "/usr/lib/python3.8/runpy.py", line 194 in _run_module_as_main
01:43:21 ---
01:43:21 Failed   <<< test_launch_ros [10.6s, exited with code -11]
```

</p>
</details>

It looks like the crashes were bad enough to fail the run, as opposed to just failing the tests. This turned the entire nightly red.

---

https://github.com/osrf/buildfarmer/issues/224

**Comment by sloretz** [comment] 2021-09-24 23:40
Possibly duplicate of #217

**Closed as completed** 2021-10-28 21:51 UTC
Labels: tests
