### ISSUE TITLE
Cannot run launch file with absolute path and arguments

### ISSUE THREAD

**Issue by AzaelCicero** [ros2/launch_ros#231] opened 2021-04-15 13:03 UTC
## Bug report

**Required Info:**

- Operating System:
  Ubuntu 20.03
- Installation type:
  Binaries
- Version or commit hash:
  - foxy
- DDS implementation:
  - Cyclone

#### Steps to reproduce issue
Just try to run launch file with absolute path and some arguments:
``` ros2 launch /absolute/path/to/launch.launch.py argument:=value ```

#### Expected behavior
Launch file will be executed. 
#### Actual behavior
Launch file will be treated as package and argument as launch file. 

#### Additional information
https://github.com/ros2/launch_ros/blob/1e34700d86ed483a7b4bac5b5468dd671cd773d9/ros2launch/ros2launch/command/launch.py#L115-L128
Issue is in code detecting if we are dealing with single file or not. Because of the bug in ament_index_python https://github.com/ament/ament_index/issues/72, code will think that we are dealing with package.

**Comment by clalancette** [comment] 2021-04-15 14:25
This is a duplicate of #221 , so closing.

**Closed by clalancette** 2021-04-15 14:25 UTC
