### ISSUE TITLE
test_launch_ros tests fail when using nightly docker image

### ISSUE THREAD

**Issue by pbaughman** [ros2/launch_ros#125] opened 2020-02-20 16:02 UTC
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 16.04
- Installation type:
  - Mostly binaries.  launch_ros built from source
- Version or commit hash:
  - launch_ros: 93b242cc02d1a9b3c31e62831f1587aac4bcbd81
  - Nightly docker image ed821d8fbcf3 (yesterday)
  - Nightly docker image 0f21b27cbc11 (today)
- DDS implementation:
  - N/A
- Client library (if applicable):
  - N/A

#### Steps to reproduce issue

```
pete@pete-VirtualBox:~$ docker pull osrf/ros2:nightly
pete@pete-VirtualBox:~$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
osrf/ros2           nightly             0f21b27cbc11        23 minutes ago      3.62GB
. . . 
pete@pete-VirtualBox:~$ docker run --rm -it -v ~/launch_ros:/launch_ros osrf/ros2:nightly

root@1b2a1736429f:/# cd launch_ros/
root@1b2a1736429f:/launch_ros# colcon build
root@1b2a1736429f:/launch_ros# colcon test
Starting >>> launch_ros
Finished <<< launch_ros [4.76s]          
Starting >>> launch_testing_ros
Starting >>> ros2launch
Starting >>> test_launch_ros                                  
Finished <<< ros2launch [3.88s]                               
Finished <<< test_launch_ros [5.58s]    [ with test failures ]
Finished <<< launch_testing_ros [11.5s]            
                      
Summary: 4 packages finished [16.7s]
  1 package had test failures: test_launch_ros
root@1b2a1736429f:/launch_ros# colcon test-result --verbose
. . .
[ERROR] [launch]: Caught exception in launch (see debug for traceback): package 'demo_nodes_py' found at '/opt/ros/foxy', but libexec directory '/opt/ros/foxy/lib/demo_nodes_py' does not exist
```

#### Expected behavior
These tests should pass, I'm running them unmodified

#### Actual behavior
It looks like something is wrong with how demo_nodes_py is used or maybe built

#### Additional information
Maybe this is helpful:
```
root@1b2a1736429f:/launch_ros# find /opt -iname demo_nodes_py
/opt/ros/foxy/lib/python3.6/site-packages/demo_nodes_py
/opt/ros/foxy/share/demo_nodes_py
/opt/ros/foxy/share/colcon-core/packages/demo_nodes_py
/opt/ros/foxy/share/ament_index/resource_index/packages/demo_nodes_py
```

It looks like the correct path might be /opt/ros/foxy/lib/python3.6/site-packages/demo_nodes_py instead of /opt/ros/foxy/lib/demo_nodes_py?

**Comment by dirk-thomas** [comment] 2020-02-20 16:06
Duplicate of ros2/build_cop#266.

**Closed by dirk-thomas** 2020-02-20 16:06 UTC
